import SwiftUI

// MARK: - ZodiakLogoVariant
// Fonte: Zodiak Design System – Capgemini (visual-assets/logo/)
//
// Usage rules (spec):
//   • Full color is preferred. Use white only when accessibility requires it.
//   • Never display the wordmark below 175pt width.
//   • Use the spade symbol only when space is too constrained for the full logo,
//     and only when the full logo has already appeared elsewhere on the page.
//   • Do not use logos in unapproved colors or reconfigurations.
//   • The spade minimum height is 24pt.

enum ZodiakLogoVariant: CaseIterable {
    // MARK: Primary Capgemini logos
    /// Full Capgemini wordmark + spade — preferred logo. Min width: 175pt.
    case capgemini
    /// Spade symbol only — use when space is constrained. Min height: 24pt.
    case spade

    // MARK: Capgemini entity logos
    /// Capgemini Invent wordmark. Min width: 175pt.
    case capgeminiInvent
    /// Capgemini Engineering wordmark. Min width: 175pt.
    case capgeminiEngineering

    // MARK: Partner / subsidiary logos
    /// Sogeti wordmark.
    case sogeti
    /// frog (design consultancy) wordmark.
    case frog
    /// Cambridge Consultants wordmark.
    case cambridgeConsultants
    /// Purpose wordmark.
    case purpose
    /// Capgemini University wordmark.
    case university
    /// Capgemini Research Institute wordmark.
    case researchInstitute
    /// Capgemini Ventures wordmark.
    case ventures
    /// Applied Innovation Exchange wordmark.
    case appliedInnovationExchange

    // MARK: - Asset name
    /// Matches the slug generated by scripts/import-visual-assets.sh
    var imageName: String {
        switch self {
        case .capgemini:                  return "zodiak-logo-capgemini-logo"
        case .spade:                      return "zodiak-logo-spade"
        case .capgeminiInvent:            return "zodiak-logo-capgemini-invent"
        case .capgeminiEngineering:       return "zodiak-logo-capgemini-engineering"
        case .sogeti:                     return "zodiak-logo-sogeti"
        case .frog:                       return "zodiak-logo-frog"
        case .cambridgeConsultants:       return "zodiak-logo-cambridge-consultants"
        case .purpose:                    return "zodiak-logo-purpose"
        case .university:                 return "zodiak-logo-university"
        case .researchInstitute:          return "zodiak-logo-research-institute"
        case .ventures:                   return "zodiak-logo-ventures"
        case .appliedInnovationExchange:  return "zodiak-logo-applied-innovation-exchange"
        }
    }

    // MARK: - Layout constraints (spec)
    /// True for the spade-only symbol (height-constrained). All others are wordmarks (width-constrained).
    var isSymbol: Bool { self == .spade }

    /// Minimum width in points. Applies to wordmarks only. Spec: 175pt.
    var minimumWidth: CGFloat? { isSymbol ? nil : 175 }

    /// Minimum height in points. Applies to the spade symbol only. Spec: 24pt.
    var minimumHeight: CGFloat? { isSymbol ? 24 : nil }

    // MARK: - Accessibility
    var accessibilityLabel: String {
        switch self {
        case .capgemini:                  return "Capgemini logo"
        case .spade:                      return "Capgemini spade symbol"
        case .capgeminiInvent:            return "Capgemini Invent logo"
        case .capgeminiEngineering:       return "Capgemini Engineering logo"
        case .sogeti:                     return "Sogeti logo"
        case .frog:                       return "frog logo"
        case .cambridgeConsultants:       return "Cambridge Consultants logo"
        case .purpose:                    return "Purpose logo"
        case .university:                 return "Capgemini University logo"
        case .researchInstitute:          return "Capgemini Research Institute logo"
        case .ventures:                   return "Capgemini Ventures logo"
        case .appliedInnovationExchange:  return "Applied Innovation Exchange logo"
        }
    }

    // MARK: - Display name
    var displayName: String {
        switch self {
        case .capgemini:                  return "Capgemini"
        case .spade:                      return "Capgemini Spade"
        case .capgeminiInvent:            return "Capgemini Invent"
        case .capgeminiEngineering:       return "Capgemini Engineering"
        case .sogeti:                     return "Sogeti"
        case .frog:                       return "frog"
        case .cambridgeConsultants:       return "Cambridge Consultants"
        case .purpose:                    return "Purpose"
        case .university:                 return "Capgemini University"
        case .researchInstitute:          return "Capgemini Research Institute"
        case .ventures:                   return "Capgemini Ventures"
        case .appliedInnovationExchange:  return "Applied Innovation Exchange"
        }
    }
}
