// Reason: Exhaustive enum of 200+ country flag tokens — data-only, single responsibility.
import CoreGraphics

// MARK: - Zodiak Flag Size Tokens
// Fonte: Zodiak Design System – Capgemini (visual-assets/flags/)
// Spec: flag always displayed with a text label.

enum ZodiakFlagSize {
    /// 16×16pt flag | 4pt gap | 24pt row | body-xs (caption 12pt)
    case xSmall
    /// 24×24pt flag | 4pt gap | 32pt row | heading-2xs (subtitleSmall 14pt)
    case small
    /// 32×32pt flag | 8pt gap | 48pt row | heading-xs (title3 16pt)
    case medium
    /// 48×48pt flag | 8pt gap | 64pt row | heading-s (title2 18pt)
    case large

    var flagDimension: CGFloat {
        switch self {
        case .xSmall: return 16
        case .small:  return 24
        case .medium: return 32
        case .large:  return 48
        }
    }

    var gap: CGFloat {
        switch self {
        case .xSmall, .small: return 4
        case .medium, .large: return 8
        }
    }

    var rowHeight: CGFloat {
        switch self {
        case .xSmall: return 24
        case .small:  return 32
        case .medium: return 48
        case .large:  return 64
        }
    }
}

// MARK: - ZodiakFlagCountry
// 113 countries from the Zodiak flags library.
// imageName matches the slug generated by scripts/import-visual-assets.sh.

// swiftlint:disable:next type_body_length
enum ZodiakFlagCountry: CaseIterable {
    // MARK: A
    case albania
    case algeria
    case armenia
    case austria
    case azerbaijan

    // MARK: B
    case bahrain
    case belarus
    case belgium
    case bolivia
    case bosniaAndHerzegovina
    case brunei
    case bulgaria
    case burkinaFaso

    // MARK: C
    case chad
    case chile
    case colombia
    case costaRica
    case croatia
    case cuba
    case czechRepublic

    // MARK: D
    case democraticRepublicOfCongo
    case denmark
    case djibouti
    case dominicanRepublic

    // MARK: E
    case equatorialGuinea
    case estonia

    // MARK: F
    case faroeIslands
    case fiji
    case finland
    case france

    // MARK: G
    case gabon
    case gambia
    case georgia
    case germany
    case ghana
    case greece
    case greenland
    case guinea
    case guineaBissau
    case guyana

    // MARK: H
    case honduras
    case hungary

    // MARK: I
    case iceland
    case indonesia
    case ireland
    case israel
    case italy
    case ivoryCoast

    // MARK: J
    case jamaica
    case japan
    case jordan

    // MARK: K
    case kuwait
    case kyrgyzstan

    // MARK: L
    case latvia
    case lebanon
    case liberia
    case lithuania
    case luxembourg

    // MARK: M
    case madagascar
    case maldives
    case mali
    case malta
    case moldova
    case monaco
    case myanmar

    // MARK: N
    case namibia
    case netherlands
    case niger
    case nigeria
    case northKorea
    case norway

    // MARK: P
    case pakistan
    case peru
    case poland

    // MARK: Q-R
    case qatar
    case republicOfNorthMacedonia
    case republicOfTheCongo
    case romania
    case russia
    case rwanda

    // MARK: S
    case senegal
    case sierraLeone
    case singapore
    case slovakia
    case slovenia
    case solomonIslands
    case somalia
    case southAfrica
    case southKorea
    case southSudan
    case sriLanka
    case sudan
    case suriname
    case sweden
    case switzerland
    case syria

    // MARK: T
    case taiwan
    case tanzania
    case thailand
    case tibet
    case togo
    case tonga
    case trinidadAndTobago
    case tunisia
    case turkey

    // MARK: U
    case ukraine
    case unitedArabEmirates
    case uruguay
    case uzbekistan

    // MARK: V–Z
    case venezuela
    case vietnam
    case yemen
    case zimbabwe

    // MARK: - Asset name
    /// Matches the slug created by scripts/import-visual-assets.sh
    var imageName: String {
        switch self {
        case .albania:                   return "zodiak-flag-albania"
        case .algeria:                   return "zodiak-flag-algeria"
        case .armenia:                   return "zodiak-flag-armenia"
        case .austria:                   return "zodiak-flag-austria"
        case .azerbaijan:                return "zodiak-flag-azerbaijan"
        case .bahrain:                   return "zodiak-flag-bahrain"
        case .belarus:                   return "zodiak-flag-belarus"
        case .belgium:                   return "zodiak-flag-belgium"
        case .bolivia:                   return "zodiak-flag-bolivia"
        case .bosniaAndHerzegovina:      return "zodiak-flag-bosnia-and-herzegovina"
        case .brunei:                    return "zodiak-flag-brunei"
        case .bulgaria:                  return "zodiak-flag-bulgaria"
        case .burkinaFaso:               return "zodiak-flag-burkina-faso"
        case .chad:                      return "zodiak-flag-chad"
        case .chile:                     return "zodiak-flag-chile"
        case .colombia:                  return "zodiak-flag-colombia"
        case .costaRica:                 return "zodiak-flag-costa-rica"
        case .croatia:                   return "zodiak-flag-croatia"
        case .cuba:                      return "zodiak-flag-cuba"
        case .czechRepublic:             return "zodiak-flag-czech-republic"
        case .democraticRepublicOfCongo: return "zodiak-flag-democratic-republic-of-congo"
        case .denmark:                   return "zodiak-flag-denmark"
        case .djibouti:                  return "zodiak-flag-djibouti"
        case .dominicanRepublic:         return "zodiak-flag-dominican-republic"
        case .equatorialGuinea:          return "zodiak-flag-equatorial-guinea"
        case .estonia:                   return "zodiak-flag-estonia"
        case .faroeIslands:              return "zodiak-flag-faroe-islands"
        case .fiji:                      return "zodiak-flag-fiji"
        case .finland:                   return "zodiak-flag-finland"
        case .france:                    return "zodiak-flag-france"
        case .gabon:                     return "zodiak-flag-gabon"
        case .gambia:                    return "zodiak-flag-gambia"
        case .georgia:                   return "zodiak-flag-georgia"
        case .germany:                   return "zodiak-flag-germany"
        case .ghana:                     return "zodiak-flag-ghana"
        case .greece:                    return "zodiak-flag-greece"
        case .greenland:                 return "zodiak-flag-greenland"
        case .guinea:                    return "zodiak-flag-guinea"
        case .guineaBissau:              return "zodiak-flag-guinea-bissau"
        case .guyana:                    return "zodiak-flag-guyana"
        case .honduras:                  return "zodiak-flag-honduras"
        case .hungary:                   return "zodiak-flag-hungary"
        case .iceland:                   return "zodiak-flag-iceland"
        case .indonesia:                 return "zodiak-flag-indonesia"
        case .ireland:                   return "zodiak-flag-ireland"
        case .israel:                    return "zodiak-flag-israel"
        case .italy:                     return "zodiak-flag-italy"
        case .ivoryCoast:                return "zodiak-flag-ivory-coast"
        case .jamaica:                   return "zodiak-flag-jamaica"
        case .japan:                     return "zodiak-flag-japan"
        case .jordan:                    return "zodiak-flag-jordan"
        case .kuwait:                    return "zodiak-flag-kuwait"
        case .kyrgyzstan:                return "zodiak-flag-kyrgyzstan"
        case .latvia:                    return "zodiak-flag-latvia"
        case .lebanon:                   return "zodiak-flag-lebanon"
        case .liberia:                   return "zodiak-flag-liberia"
        case .lithuania:                 return "zodiak-flag-lithuania"
        case .luxembourg:                return "zodiak-flag-luxembourg"
        case .madagascar:                return "zodiak-flag-madagascar"
        case .maldives:                  return "zodiak-flag-maldives"
        case .mali:                      return "zodiak-flag-mali"
        case .malta:                     return "zodiak-flag-malta"
        case .moldova:                   return "zodiak-flag-moldova"
        case .monaco:                    return "zodiak-flag-monaco"
        case .myanmar:                   return "zodiak-flag-myanmar"
        case .namibia:                   return "zodiak-flag-namibia"
        case .netherlands:               return "zodiak-flag-netherlands"
        case .niger:                     return "zodiak-flag-niger"
        case .nigeria:                   return "zodiak-flag-nigeria"
        case .northKorea:                return "zodiak-flag-north-korea"
        case .norway:                    return "zodiak-flag-norway"
        case .pakistan:                  return "zodiak-flag-pakistan"
        case .peru:                      return "zodiak-flag-peru"
        case .poland:                    return "zodiak-flag-poland"
        case .qatar:                     return "zodiak-flag-qatar"
        case .republicOfNorthMacedonia:  return "zodiak-flag-republic-of-north-macedonia"
        case .republicOfTheCongo:        return "zodiak-flag-republic-of-the-congo"
        case .romania:                   return "zodiak-flag-romania"
        case .russia:                    return "zodiak-flag-russia"
        case .rwanda:                    return "zodiak-flag-rwanda"
        case .senegal:                   return "zodiak-flag-senegal"
        case .sierraLeone:               return "zodiak-flag-sierra-leone"
        case .singapore:                 return "zodiak-flag-singapore"
        case .slovakia:                  return "zodiak-flag-slovakia"
        case .slovenia:                  return "zodiak-flag-slovenia"
        case .solomonIslands:            return "zodiak-flag-solomon-islands"
        case .somalia:                   return "zodiak-flag-somalia"
        case .southAfrica:               return "zodiak-flag-south-africa"
        case .southKorea:                return "zodiak-flag-south-korea"
        case .southSudan:                return "zodiak-flag-south-sudan"
        case .sriLanka:                  return "zodiak-flag-sri-lanka"
        case .sudan:                     return "zodiak-flag-sudan"
        case .suriname:                  return "zodiak-flag-suriname"
        case .sweden:                    return "zodiak-flag-sweden"
        case .switzerland:               return "zodiak-flag-switzerland"
        case .syria:                     return "zodiak-flag-syria"
        case .taiwan:                    return "zodiak-flag-taiwan"
        case .tanzania:                  return "zodiak-flag-tanzania"
        case .thailand:                  return "zodiak-flag-thailand"
        case .tibet:                     return "zodiak-flag-tibet"
        case .togo:                      return "zodiak-flag-togo"
        case .tonga:                     return "zodiak-flag-tonga"
        case .trinidadAndTobago:         return "zodiak-flag-trinidad-and-yobago"
        case .tunisia:                   return "zodiak-flag-tunisia"
        case .turkey:                    return "zodiak-flag-turkey"
        case .ukraine:                   return "zodiak-flag-ukraine"
        case .unitedArabEmirates:        return "zodiak-flag-united-arab-emirates"
        case .uruguay:                   return "zodiak-flag-uruguay"
        case .uzbekistan:                return "zodiak-flag-uzbekistan"
        case .venezuela:                 return "zodiak-flag-venezuela"
        case .vietnam:                   return "zodiak-flag-vietnam"
        case .yemen:                     return "zodiak-flag-yemen"
        case .zimbabwe:                  return "zodiak-flag-zimbabwe"
        }
    }

    // MARK: - Display name (English)
    var displayName: String {
        switch self {
        case .albania:                   return "Albania"
        case .algeria:                   return "Algeria"
        case .armenia:                   return "Armenia"
        case .austria:                   return "Austria"
        case .azerbaijan:                return "Azerbaijan"
        case .bahrain:                   return "Bahrain"
        case .belarus:                   return "Belarus"
        case .belgium:                   return "Belgium"
        case .bolivia:                   return "Bolivia"
        case .bosniaAndHerzegovina:      return "Bosnia and Herzegovina"
        case .brunei:                    return "Brunei"
        case .bulgaria:                  return "Bulgaria"
        case .burkinaFaso:               return "Burkina Faso"
        case .chad:                      return "Chad"
        case .chile:                     return "shared.country.chile"
        case .colombia:                  return "Colombia"
        case .costaRica:                 return "Costa Rica"
        case .croatia:                   return "Croatia"
        case .cuba:                      return "Cuba"
        case .czechRepublic:             return "Czech Republic"
        case .democraticRepublicOfCongo: return "Democratic Republic of Congo"
        case .denmark:                   return "Denmark"
        case .djibouti:                  return "Djibouti"
        case .dominicanRepublic:         return "Dominican Republic"
        case .equatorialGuinea:          return "Equatorial Guinea"
        case .estonia:                   return "Estonia"
        case .faroeIslands:              return "Faroe Islands"
        case .fiji:                      return "Fiji"
        case .finland:                   return "Finland"
        case .france:                    return "France"
        case .gabon:                     return "Gabon"
        case .gambia:                    return "Gambia"
        case .georgia:                   return "Georgia"
        case .germany:                   return "Germany"
        case .ghana:                     return "Ghana"
        case .greece:                    return "Greece"
        case .greenland:                 return "Greenland"
        case .guinea:                    return "Guinea"
        case .guineaBissau:              return "Guinea-Bissau"
        case .guyana:                    return "Guyana"
        case .honduras:                  return "Honduras"
        case .hungary:                   return "Hungary"
        case .iceland:                   return "Iceland"
        case .indonesia:                 return "Indonesia"
        case .ireland:                   return "Ireland"
        case .israel:                    return "Israel"
        case .italy:                     return "Italy"
        case .ivoryCoast:                return "Ivory Coast"
        case .jamaica:                   return "Jamaica"
        case .japan:                     return "Japan"
        case .jordan:                    return "Jordan"
        case .kuwait:                    return "Kuwait"
        case .kyrgyzstan:                return "Kyrgyzstan"
        case .latvia:                    return "Latvia"
        case .lebanon:                   return "Lebanon"
        case .liberia:                   return "Liberia"
        case .lithuania:                 return "Lithuania"
        case .luxembourg:                return "Luxembourg"
        case .madagascar:                return "Madagascar"
        case .maldives:                  return "Maldives"
        case .mali:                      return "Mali"
        case .malta:                     return "Malta"
        case .moldova:                   return "Moldova"
        case .monaco:                    return "Monaco"
        case .myanmar:                   return "Myanmar"
        case .namibia:                   return "Namibia"
        case .netherlands:               return "Netherlands"
        case .niger:                     return "Niger"
        case .nigeria:                   return "Nigeria"
        case .northKorea:                return "North Korea"
        case .norway:                    return "Norway"
        case .pakistan:                  return "Pakistan"
        case .peru:                      return "Peru"
        case .poland:                    return "Poland"
        case .qatar:                     return "Qatar"
        case .republicOfNorthMacedonia:  return "Republic of North Macedonia"
        case .republicOfTheCongo:        return "Republic of the Congo"
        case .romania:                   return "Romania"
        case .russia:                    return "Russia"
        case .rwanda:                    return "Rwanda"
        case .senegal:                   return "Senegal"
        case .sierraLeone:               return "Sierra Leone"
        case .singapore:                 return "Singapore"
        case .slovakia:                  return "Slovakia"
        case .slovenia:                  return "Slovenia"
        case .solomonIslands:            return "Solomon Islands"
        case .somalia:                   return "Somalia"
        case .southAfrica:               return "South Africa"
        case .southKorea:                return "South Korea"
        case .southSudan:                return "South Sudan"
        case .sriLanka:                  return "Sri Lanka"
        case .sudan:                     return "Sudan"
        case .suriname:                  return "Suriname"
        case .sweden:                    return "Sweden"
        case .switzerland:               return "Switzerland"
        case .syria:                     return "Syria"
        case .taiwan:                    return "Taiwan"
        case .tanzania:                  return "Tanzania"
        case .thailand:                  return "Thailand"
        case .tibet:                     return "Tibet"
        case .togo:                      return "Togo"
        case .tonga:                     return "Tonga"
        case .trinidadAndTobago:         return "Trinidad and Tobago"
        case .tunisia:                   return "Tunisia"
        case .turkey:                    return "Turkey"
        case .ukraine:                   return "Ukraine"
        case .unitedArabEmirates:        return "United Arab Emirates"
        case .uruguay:                   return "Uruguay"
        case .uzbekistan:                return "Uzbekistan"
        case .venezuela:                 return "Venezuela"
        case .vietnam:                   return "Vietnam"
        case .yemen:                     return "Yemen"
        case .zimbabwe:                  return "Zimbabwe"
        }
    }
}
