// swiftlint:disable file_length
import Foundation

// MARK: - Icon Common Uses Map (pt-BR)

let iconCommonUsesMapPT: [ZodiakIcon: [String]] = [
    // MARK: Navigation
    .arrowDown: ["Expandir", "Scroll", "Ordenação"],
    .arrowDownLeft: ["Diagonal", "Voltar diagonal", "Seta"],
    .arrowDownRight: ["Diagonal", "Avançar diagonal", "Seta"],
    .arrowDownUp: ["Reordenar", "Arrastar", "Swap"],
    .arrowLeft: ["Voltar", "Navegação", "Carrossel"],
    .arrowLeftRight: ["Redimensionar", "Mover", "Swap horizontal"],
    .arrowRight: ["Avançar", "Navegação", "Carrossel"],
    .arrowUp: ["Recolher", "Scroll", "Ordenação"],
    .arrowUpLeft: ["Diagonal", "Voltar diagonal", "Seta"],
    .arrowUpRight: ["Link externo", "Diagonal", "Seta"],
    .arrowUndoDownLeft: ["Desfazer", "Voltar", "Histórico"],
    .arrowUndoDownRight: ["Refazer", "Avançar", "Histórico"],
    .arrowUndoUpLeft: ["Desfazer", "Voltar", "Histórico"],
    .arrowUndoUpRight: ["Refazer", "Avançar", "Histórico"],
    .arrowsReload01: ["Atualizar", "Sincronizar", "Retry"],
    .arrowsReload02: ["Atualizar", "Sincronizar", "Retry"],
    .chevronDown: ["Expandir", "Dropdown", "Acordeão"],
    .chevronFirstPage: ["Primeira página", "Início", "Paginação"],
    .chevronLastPage: ["Última página", "Fim", "Paginação"],
    .chevronLeft: ["Voltar", "Carrossel", "Navegação"],
    .chevronRight: ["Avançar", "Carrossel", "Navegação"],
    .chevronUp: ["Recolher", "Dropdown", "Acordeão"],
    .compass: ["Explorar", "Descobrir", "GPS"],
    .expand: ["Tela cheia", "Expandir", "Ampliar"],
    .externalLink: ["Link externo", "Nova aba", "URL"],
    .hamburger: ["Menu hambúrguer", "Navegação", "Sidebar"],
    .house: ["Início", "Home", "Dashboard"],
    .map: ["Mapa", "Localização", "Navegação"],
    .mapPin: ["Localização", "Mapa", "GPS"],
    .moreGrid: ["Grid", "Grade", "Visualização"],
    .moreHorizontal: ["Mais opções", "Menu contextual", "Overflow"],
    .moreVertical: ["Mais opções", "Menu contextual", "Overflow"],
    .navigation: ["Navegação", "Direção", "GPS"],
    .shrink: ["Minimizar", "Recolher", "Reduzir"],
    .sortAscending: ["Ordenar A-Z", "Crescente", "Ordenação"],
    .sortDescending: ["Ordenar Z-A", "Decrescente", "Ordenação"],
    .unfoldLess: ["Recolher tudo", "Colapsar", "Acordeão"],
    .unfoldMore: ["Expandir tudo", "Mostrar mais", "Acordeão"],

    // MARK: Communication
    .bell: ["Notificações", "Alertas", "Sininho"],
    .bellNotification: ["Notificações", "Badge", "Alertas"],
    .bellOff: ["Silenciar", "Desativar alertas", "Mudo"],
    .bellRing: ["Notificação ativa", "Toque", "Alerta"],
    .chatCircle: ["Chat", "Mensagem", "Conversa"],
    .chatCircleAdd: ["Novo chat", "Iniciar conversa", "Mensagem"],
    .chatCircleCheck: ["Mensagem lida", "Confirmação", "Chat"],
    .chatCircleClose: ["Fechar chat", "Encerrar conversa", "Chat"],
    .chatCircleDots: ["Digitando", "Chat", "Mensagem"],
    .chatCircleRemove: ["Remover chat", "Excluir conversa", "Chat"],
    .chatConversationCircle: ["Conversa", "Duplo chat", "Mensagens"],
    .headphones: ["Áudio", "Fones", "Voz"],
    .mail: ["E-mail", "Mensagem", "Contato"],
    .mailOpen: ["E-mail aberto", "Lido", "Mensagem"],
    .mention: ["Menção", "Arroba", "@usuário"],
    .paperclipAttachment: ["Anexo", "Arquivo", "Attachment"],
    .paperPlane: ["Enviar", "Submeter", "Compartilhar"],
    .phone: ["Telefone", "Chamada", "Contato"],
    .share: ["Compartilhar", "Exportar", "Social"],
    .shareAndroid: ["Compartilhar", "Android", "Exportar"],
    .shareiOSExport: ["Compartilhar", "iOS", "Exportar"],

    // MARK: Files & Data
    .archive: ["Arquivo morto", "Armazenar", "Histórico"],
    .cloud: ["Nuvem", "Cloud", "Armazenamento online"],
    .cloudAdd: ["Adicionar à nuvem", "Upload", "Sync"],
    .cloudCheck: ["Nuvem sincronizada", "Backup", "Cloud"],
    .cloudClose: ["Nuvem indisponível", "Erro cloud", "Offline"],
    .cloudDownload: ["Download da nuvem", "Baixar", "Cloud"],
    .cloudOff: ["Nuvem offline", "Sem sync", "Desconectado"],
    .cloudRemove: ["Remover da nuvem", "Excluir cloud", "Sync"],
    .cloudUpload: ["Upload", "Enviar arquivo", "Importar"],
    .data: ["Dados", "Base de dados", "Armazenamento"],
    .download: ["Download", "Exportar", "Salvar arquivo"],
    .downloadPackage: ["Download", "Pacote", "Instalar"],
    .fileAdd: ["Novo arquivo", "Criar arquivo", "Documento"],
    .fileBlank: ["Arquivo vazio", "Documento", "Novo"],
    .fileCheck: ["Arquivo aprovado", "Validado", "Documento"],
    .fileClose: ["Fechar arquivo", "Remover", "Documento"],
    .fileCode: ["Código", "Programação", "Script"],
    .fileDocument: ["Documento", "Relatório", "Texto"],
    .fileDownload: ["Download", "Baixar arquivo", "Salvar"],
    .fileEdit: ["Editar arquivo", "Modificar", "Documento"],
    .fileRemove: ["Remover arquivo", "Excluir", "Documento"],
    .fileSearch: ["Buscar arquivo", "Pesquisa", "Documento"],
    .fileUpload: ["Upload", "Enviar arquivo", "Importar"],
    .files: ["Arquivos", "Documentos", "Gestão"],
    .folder: ["Pasta", "Diretório", "Organização"],
    .folderAdd: ["Nova pasta", "Criar pasta", "Diretório"],
    .folderCheck: ["Pasta aprovada", "Validada", "Diretório"],
    .folderClose: ["Fechar pasta", "Diretório", "Organização"],
    .folderCode: ["Pasta de código", "Projeto", "Dev"],
    .folderDocument: ["Pasta de documentos", "Arquivos", "Diretório"],
    .folderDownload: ["Download", "Baixar pasta", "Diretório"],
    .folderEdit: ["Editar pasta", "Renomear", "Diretório"],
    .folderOpen: ["Abrir pasta", "Diretório", "Arquivos"],
    .folderRemove: ["Remover pasta", "Excluir", "Diretório"],
    .folderSearch: ["Buscar pasta", "Pesquisa", "Diretório"],
    .folderUpload: ["Upload", "Enviar pasta", "Importar"],
    .folders: ["Pastas", "Diretórios", "Organização"],

    // MARK: Media
    .backward15: ["Voltar 15s", "Rewind", "Player"],
    .camera: ["Foto", "Upload de imagem", "Scanner"],
    .forward: ["Avançar", "Próximo", "Player"],
    .forward15: ["Avançar 15s", "Player", "Mídia"],
    .image: ["Imagem", "Galeria", "Mídia"],
    .layers: ["Camadas", "Stacks", "Organização"],
    .monitor: ["Monitor", "Tela", "Display"],
    .monitorPlay: ["Vídeo", "Gravação", "Player"],
    .pause: ["Pausar", "Player", "Mídia"],
    .pauseFilled: ["Pausar", "Player", "Mídia"],
    .play: ["Play", "Player", "Mídia"],
    .playFilled: ["Play", "Player", "Mídia"],
    .rewind: ["Rebobinar", "Início", "Player"],
    .shuffle: ["Aleatório", "Shuffle", "Playlist"],
    .skipBack: ["Anterior", "Player", "Mídia"],
    .skipForward: ["Próximo", "Player", "Mídia"],
    .speed: ["Velocidade", "Playback", "Player"],
    .stop: ["Parar", "Player", "Mídia"],
    .stopFilled: ["Parar", "Player", "Mídia"],
    .swatchesPalette: ["Temas", "Cores", "Personalização"],
    .volumeMax: ["Volume alto", "Som", "Áudio"],
    .volumeMin: ["Volume baixo", "Som", "Áudio"],
    .volumeOff: ["Mudo", "Sem som", "Silencioso"],

    // MARK: AI & Social
    .ai: ["Inteligência artificial", "IA", "Machine learning"],
    .aiBrain: ["IA", "Processamento", "Machine learning"],
    .aiContent: ["Conteúdo IA", "Geração de texto", "IA"],
    .aiEditing: ["Edição IA", "Correção automática", "IA"],
    .aiGenerate: ["Gerar com IA", "Criar", "IA"],
    .aiImage: ["Imagem IA", "Arte gerada", "IA"],
    .aiLibrary: ["Biblioteca IA", "Modelos", "IA"],
    .aiMagicWand: ["Magia IA", "Transformar", "IA"],
    .aiSearch: ["Busca IA", "Pesquisa inteligente", "IA"],
    .apple: ["Apple", "iOS", "macOS"],
    .applePodcast: ["Podcasts", "Apple Podcast", "Áudio"],
    .bot: ["Bot", "Chatbot", "Automação"],
    .facebook: ["Facebook", "Social", "Rede social"],
    .figma: ["Figma", "Design", "Prototipagem"],
    .github: ["GitHub", "Código", "Repositório"],
    .glassdoor: ["Glassdoor", "Empregos", "Avaliações"],
    .globe: ["Idioma", "Web", "Internacional"],
    .google: ["Google", "Busca", "Search"],
    .googlePodcasts: ["Google Podcasts", "Áudio", "Podcast"],
    .instagram: ["Instagram", "Social", "Fotos"],
    .linkedin: ["LinkedIn", "Profissional", "Rede"],
    .messenger: ["Messenger", "Facebook", "Chat"],
    .openAIChatGPT: ["ChatGPT", "OpenAI", "IA"],
    .slack: ["Slack", "Equipe", "Mensagens"],
    .slideshare: ["SlideShare", "Apresentações", "LinkedIn"],
    .soundcloud: ["SoundCloud", "Música", "Áudio"],
    .spotify: ["Spotify", "Música", "Streaming"],
    .teams: ["Teams", "Microsoft", "Reunião"],
    .threads: ["Threads", "Instagram", "Social"],
    .tiktok: ["TikTok", "Vídeo", "Social"],
    .weChat: ["WeChat", "China", "Mensagens"],
    .weibo: ["Weibo", "China", "Social"],
    .whatsapp: ["WhatsApp", "Mensagens", "Chat"],
    .windows: ["Windows", "Microsoft", "Sistema"],
    .x: ["X", "Twitter", "Social"],
    .youtube: ["YouTube", "Vídeo", "Streaming"],

    // MARK: Actions
    .addPlus: ["Adicionar item", "Criar novo", "FAB"],
    .addToQueue: ["Adicionar à fila", "Queue", "Playlist"],
    .alarm: ["Lembretes", "Alertas", "Notificações"],
    .bold: ["Negrito", "Formatação", "Texto"],
    .bookOpen: ["Livro", "Leitura", "Conteúdo"],
    .bookmark: ["Salvar", "Favoritos", "Lista de leitura"],
    .building: ["Empresa", "Edifício", "Organização"],
    .bulb: ["Ideia", "Lâmpada", "Insight"],
    .calendarAdd: ["Adicionar evento", "Agendamento", "Data"],
    .calendarClose: ["Cancelar evento", "Remover data", "Agenda"],
    .calendarDays: ["Data", "Agendamento", "Eventos"],
    .calendarOk: ["Evento confirmado", "Agendado", "Data"],
    .calendarWeek: ["Semana", "Agenda semanal", "Calendário"],
    .chartBarVertical: ["Gráficos", "Analytics", "Dashboard"],
    .chartLine: ["Gráfico de linha", "Analytics", "Métricas"],
    .chartPie: ["Gráfico de pizza", "Analytics", "Distribuição"],
    .check: ["Confirmar", "Concluído", "Seleção"],
    .checkAll: ["Selecionar tudo", "Confirmar tudo", "Batch"],
    .checkboxCheck: ["Checkbox marcado", "Seleção", "Tarefa"],
    .checkboxUnchecked: ["Checkbox vazio", "Seleção", "Tarefa"],
    .circleCheck: ["Sucesso", "Validação", "Confirmação"],
    .circleHelp: ["Ajuda", "FAQ", "Suporte"],
    .clock: ["Horário", "Tempo", "Relógio"],
    .close: ["Fechar", "Cancelar", "Remover tag"],
    .code: ["Código", "Programação", "Dev"],
    .coffee: ["Café", "Pausa", "Break"],
    .coffeToGo: ["Café para viagem", "Take away", "Drink"],
    .command: ["Comando", "Atalho", "Terminal"],
    .cookie: ["Cookie", "Privacidade", "LGPD"],
    .copy: ["Copiar", "Duplicar", "Clipboard"],
    .creditCard: ["Pagamento", "Carteira", "Finanças"],
    .crop: ["Cortar", "Recortar", "Edição"],
    .cupcake: ["Cupcake", "Aniversário", "Celebração"],
    .desktopTower: ["Desktop", "Computador", "Hardware"],
    .devices: ["Dispositivos", "Multi-device", "Responsivo"],
    .doubleQuotes: ["Citação", "Quote", "Texto"],
    .editPencil: ["Editar", "Modificar", "Caneta"],
    .editPencilLine: ["Editar", "Modificar", "Escrever"],
    .filter: ["Filtrar", "Refinamento", "Busca avançada"],
    .firstAid: ["Primeiros socorros", "Saúde", "Emergência"],
    .flag: ["Sinalizar", "Denúncia", "Atenção"],
    .font: ["Fonte", "Tipografia", "Texto"],
    .gift: ["Presente", "Recompensa", "Promoção"],
    .heart: ["Curtir", "Favoritar", "Saúde"],
    .hide: ["Ocultar", "Esconder senha", "Privacidade"],
    .info: ["Informação", "Tooltip", "Ajuda"],
    .italic: ["Itálico", "Formatação", "Texto"],
    .keyboard: ["Teclado", "Input", "Digitação"],
    .label: ["Etiqueta", "Tag", "Classificação"],
    .laptop: ["Notebook", "Computador", "Trabalho"],
    .leaf: ["Sustentabilidade", "Eco", "Natureza"],
    .link: ["URL", "Compartilhar link", "Hyperlink"],
    .linkBreak: ["Link quebrado", "Desconectar", "URL"],
    .listAdd: ["Adicionar à lista", "Nova tarefa", "To-do"],
    .listCheck: ["Lista concluída", "Checklist", "Tarefa"],
    .listChecklist: ["Checklist", "Tarefas", "Lista"],
    .listOrdered: ["Lista ordenada", "Numerada", "Sequência"],
    .listRemove: ["Remover da lista", "Excluir tarefa", "To-do"],
    .lock: ["Segurança", "Bloqueado", "Privacidade"],
    .lockOpen: ["Desbloqueado", "Sem restrição", "Aberto"],
    .logOut: ["Sair", "Logout", "Desconectar"],
    .magnifyingGlassBlock: ["Busca bloqueada", "Sem resultado", "Pesquisa"],
    .magnifyingGlassMinus: ["Zoom out", "Reduzir", "Pesquisa"],
    .magnifyingGlassPlus: ["Zoom in", "Ampliar", "Pesquisa"],
    .mobileButton: ["Mobile", "Celular", "App"],
    .moon: ["Modo escuro", "Noite", "Sono"],
    .mouse: ["Mouse", "Cursor", "Interação"],
    .move: ["Mover", "Arrastar", "Drag"],
    .note: ["Nota", "Anotação", "Lembrete"],
    .noteEdit: ["Editar nota", "Anotação", "Escrever"],
    .noteSearch: ["Buscar nota", "Pesquisa", "Anotação"],
    .notebook: ["Caderno", "Notas", "Diário"],
    .octagonWarning: ["Aviso", "Atenção", "Erro"],
    .paragraph: ["Parágrafo", "Formatação", "Texto"],
    .planet: ["Planeta", "Global", "Mundo"],
    .printer: ["Imprimir", "Impressora", "Documento"],
    .puzzle: ["Integração", "Plugin", "Extensão"],
    .qrCode: ["QR Code", "Digitalizar", "Link"],
    .radioFill: ["Radio selecionado", "Opção", "Formulário"],
    .radioUnchecked: ["Radio vazio", "Opção", "Formulário"],
    .rainbow: ["Diversidade", "Cores", "Criatividade"],
    .redo: ["Refazer", "Avançar ação", "Histórico"],
    .removeMinus: ["Remover", "Diminuir", "Menos"],
    .ruler: ["Régua", "Medição", "Design"],
    .save: ["Salvar", "Guardar", "Disco"],
    .searchMagnifyingGlass: ["Buscar", "Pesquisa", "Filtro"],
    .selectMultiple: ["Selecionar múltiplos", "Seleção em massa", "Batch"],
    .settings: ["Configurações", "Preferências", "Ajustes"],
    .shoppingBag: ["Sacola", "Compras", "E-commerce"],
    .shoppingCart: ["Carrinho", "Compras", "E-commerce"],
    .show: ["Visualizar", "Mostrar senha", "Preview"],
    .star: ["Favoritar", "Avaliação", "Destaque"],
    .strikethrough: ["Tachado", "Formatação", "Texto"],
    .suitcase: ["Viagem", "Negócios", "Bagagem"],
    .sun: ["Modo claro", "Brilho", "Dia"],
    .switchLeft: ["Desativar", "Toggle off", "Switch"],
    .switchRight: ["Ativar", "Toggle on", "Switch"],
    .table: ["Tabela", "Dados", "Grid"],
    .tableAdd: ["Adicionar tabela", "Nova linha", "Grid"],
    .tableRemove: ["Remover tabela", "Excluir linha", "Grid"],
    .tabletButton: ["Tablet", "iPad", "Dispositivo"],
    .tag: ["Tag", "Categoria", "Classificação"],
    .text: ["Texto", "Conteúdo", "Tipografia"],
    .textAlignCenter: ["Centralizar", "Alinhamento", "Texto"],
    .textAlignJustify: ["Justificar", "Alinhamento", "Texto"],
    .textAlignLeft: ["Alinhar esquerda", "Alinhamento", "Texto"],
    .textAlignRight: ["Alinhar direita", "Alinhamento", "Texto"],
    .ticketVoucher: ["Ingresso", "Voucher", "Cupom"],
    .trashEmpty: ["Excluir", "Remover", "Lixeira"],
    .trashFull: ["Lixeira cheia", "Excluir", "Remover"],
    .trendingDown: ["Queda", "Tendência negativa", "Métricas"],
    .trendingUp: ["Alta", "Crescimento", "Métricas"],
    .underline: ["Sublinhado", "Formatação", "Texto"],
    .undo: ["Desfazer", "Voltar ação", "Histórico"],
    .user: ["Perfil", "Avatar", "Conta"],
    .userAdd: ["Adicionar usuário", "Novo membro", "Convite"],
    .userCardID: ["Crachá", "Identidade", "Perfil"],
    .userCheck: ["Usuário aprovado", "Verificado", "Confirmado"],
    .userClose: ["Usuário removido", "Banido", "Bloqueado"],
    .userRemove: ["Remover usuário", "Excluir membro", "Conta"],
    .userVoice: ["Narrador", "Acessibilidade", "Voz"],
    .users: ["Grupo", "Time", "Comunidade"],
    .waterDrop: ["Água", "Hidratação", "Sustentabilidade"],
    .wifiHigh: ["Conexão", "Rede", "Internet"],
    .wifiOff: ["Sem Wi-Fi", "Offline", "Desconectado"],
    .wifiProblem: ["Problema de Wi-Fi", "Sinal fraco", "Conexão"]
]

// MARK: - Icon Common Uses Map (en)

let iconCommonUsesMapEN: [ZodiakIcon: [String]] = [
    // MARK: Navigation
    .arrowDown: ["Expand", "Scroll", "Sort"],
    .arrowDownLeft: ["Diagonal", "Back diagonal", "Arrow"],
    .arrowDownRight: ["Diagonal", "Forward diagonal", "Arrow"],
    .arrowDownUp: ["Reorder", "Drag", "Swap"],
    .arrowLeft: ["Back", "Navigation", "Carousel"],
    .arrowLeftRight: ["Resize", "Move", "Horizontal swap"],
    .arrowRight: ["Forward", "Navigation", "Carousel"],
    .arrowUp: ["Collapse", "Scroll", "Sort"],
    .arrowUpLeft: ["Diagonal", "Back diagonal", "Arrow"],
    .arrowUpRight: ["External link", "Diagonal", "Arrow"],
    .arrowUndoDownLeft: ["Undo", "Back", "History"],
    .arrowUndoDownRight: ["Redo", "Forward", "History"],
    .arrowUndoUpLeft: ["Undo", "Back", "History"],
    .arrowUndoUpRight: ["Redo", "Forward", "History"],
    .arrowsReload01: ["Refresh", "Sync", "Retry"],
    .arrowsReload02: ["Refresh", "Sync", "Retry"],
    .chevronDown: ["Expand", "Dropdown", "Accordion"],
    .chevronFirstPage: ["First page", "Start", "Pagination"],
    .chevronLastPage: ["Last page", "End", "Pagination"],
    .chevronLeft: ["Back", "Carousel", "Navigation"],
    .chevronRight: ["Forward", "Carousel", "Navigation"],
    .chevronUp: ["Collapse", "Dropdown", "Accordion"],
    .compass: ["Explore", "Discover", "GPS"],
    .expand: ["Full screen", "Expand", "Zoom in"],
    .externalLink: ["External link", "New tab", "URL"],
    .hamburger: ["Hamburger menu", "Navigation", "Sidebar"],
    .house: ["Home", "Start", "Dashboard"],
    .map: ["Map", "Location", "Navigation"],
    .mapPin: ["Location", "Map", "GPS"],
    .moreGrid: ["Grid", "Grid layout", "View"],
    .moreHorizontal: ["More options", "Context menu", "Overflow"],
    .moreVertical: ["More options", "Context menu", "Overflow"],
    .navigation: ["Navigation", "Direction", "GPS"],
    .shrink: ["Minimize", "Shrink", "Reduce"],
    .sortAscending: ["Sort A-Z", "Ascending", "Sort"],
    .sortDescending: ["Sort Z-A", "Descending", "Sort"],
    .unfoldLess: ["Collapse all", "Collapse", "Accordion"],
    .unfoldMore: ["Expand all", "Show more", "Accordion"],

    // MARK: Communication
    .bell: ["Notifications", "Alerts", "Bell"],
    .bellNotification: ["Notifications", "Badge", "Alerts"],
    .bellOff: ["Mute notifications", "Disable alerts", "Silent"],
    .bellRing: ["Active notification", "Ring", "Alert"],
    .chatCircle: ["Chat", "Message", "Conversation"],
    .chatCircleAdd: ["New chat", "Start conversation", "Message"],
    .chatCircleCheck: ["Message read", "Confirmation", "Chat"],
    .chatCircleClose: ["Close chat", "End conversation", "Chat"],
    .chatCircleDots: ["Typing", "Chat", "Message"],
    .chatCircleRemove: ["Remove chat", "Delete conversation", "Chat"],
    .chatConversationCircle: ["Conversation", "Dual chat", "Messages"],
    .headphones: ["Audio", "Headphones", "Voice"],
    .mail: ["Email", "Message", "Contact"],
    .mailOpen: ["Open email", "Read", "Message"],
    .mention: ["Mention", "At sign", "@user"],
    .paperclipAttachment: ["Attachment", "File", "Clip"],
    .paperPlane: ["Send", "Submit", "Share"],
    .phone: ["Phone", "Call", "Contact"],
    .share: ["Share", "Export", "Social"],
    .shareAndroid: ["Share", "Android share", "Export"],
    .shareiOSExport: ["Share", "iOS share", "Export"],

    // MARK: Files & Data
    .archive: ["Archive", "Store", "History"],
    .cloud: ["Cloud", "Storage", "Online"],
    .cloudAdd: ["Add to cloud", "Upload", "Sync"],
    .cloudCheck: ["Cloud synced", "Backup", "Cloud"],
    .cloudClose: ["Cloud unavailable", "Cloud error", "Offline"],
    .cloudDownload: ["Download from cloud", "Cloud", "Backup"],
    .cloudOff: ["Cloud offline", "No sync", "Disconnected"],
    .cloudRemove: ["Remove from cloud", "Delete cloud", "Sync"],
    .cloudUpload: ["Upload", "Send file", "Import"],
    .data: ["Data", "Database", "Storage"],
    .download: ["Download", "Export", "Save file"],
    .downloadPackage: ["Download", "Package", "Install"],
    .fileAdd: ["New file", "Create file", "Document"],
    .fileBlank: ["Blank file", "Document", "New"],
    .fileCheck: ["File approved", "Validated", "Document"],
    .fileClose: ["Close file", "Remove", "Document"],
    .fileCode: ["Code file", "Programming", "Script"],
    .fileDocument: ["Document", "Report", "Text file"],
    .fileDownload: ["Download file", "Save", "Document"],
    .fileEdit: ["Edit file", "Modify", "Document"],
    .fileRemove: ["Remove file", "Delete", "Document"],
    .fileSearch: ["Search file", "Find", "Document"],
    .fileUpload: ["Upload file", "Import", "Document"],
    .files: ["Files", "Documents", "Management"],
    .folder: ["Folder", "Directory", "Organization"],
    .folderAdd: ["New folder", "Create folder", "Directory"],
    .folderCheck: ["Folder approved", "Validated", "Directory"],
    .folderClose: ["Close folder", "Directory", "Organization"],
    .folderCode: ["Code folder", "Project", "Dev"],
    .folderDocument: ["Documents folder", "Files", "Directory"],
    .folderDownload: ["Download folder", "Save", "Directory"],
    .folderEdit: ["Edit folder", "Rename", "Directory"],
    .folderOpen: ["Open folder", "Directory", "Files"],
    .folderRemove: ["Remove folder", "Delete", "Directory"],
    .folderSearch: ["Search folder", "Find", "Directory"],
    .folderUpload: ["Upload folder", "Import", "Directory"],
    .folders: ["Folders", "Directories", "Organization"],

    // MARK: Media
    .backward15: ["Rewind 15s", "Back 15", "Player"],
    .camera: ["Photo", "Image upload", "Scanner"],
    .forward: ["Forward", "Next", "Player"],
    .forward15: ["Forward 15s", "Player", "Media"],
    .image: ["Image", "Gallery", "Media"],
    .layers: ["Layers", "Stacks", "Organization"],
    .monitor: ["Monitor", "Screen", "Display"],
    .monitorPlay: ["Video", "Recording", "Player"],
    .pause: ["Pause", "Player", "Media"],
    .pauseFilled: ["Pause", "Player", "Media"],
    .play: ["Play", "Player", "Media"],
    .playFilled: ["Play", "Player", "Media"],
    .rewind: ["Rewind", "Start", "Player"],
    .shuffle: ["Shuffle", "Random", "Playlist"],
    .skipBack: ["Previous", "Player", "Media"],
    .skipForward: ["Next", "Player", "Media"],
    .speed: ["Speed", "Playback", "Player"],
    .stop: ["Stop", "Player", "Media"],
    .stopFilled: ["Stop", "Player", "Media"],
    .swatchesPalette: ["Themes", "Colors", "Customize"],
    .volumeMax: ["Volume high", "Sound", "Audio"],
    .volumeMin: ["Volume low", "Sound", "Audio"],
    .volumeOff: ["Mute", "No sound", "Silent"],

    // MARK: AI & Social
    .ai: ["Artificial intelligence", "AI", "Machine learning"],
    .aiBrain: ["AI", "Processing", "Machine learning"],
    .aiContent: ["AI content", "Text generation", "AI"],
    .aiEditing: ["AI editing", "Auto-correct", "AI"],
    .aiGenerate: ["Generate with AI", "Create", "AI"],
    .aiImage: ["AI image", "Generated art", "AI"],
    .aiLibrary: ["AI library", "Models", "AI"],
    .aiMagicWand: ["AI magic", "Transform", "AI"],
    .aiSearch: ["AI search", "Smart search", "AI"],
    .apple: ["Apple", "iOS", "macOS"],
    .applePodcast: ["Podcasts", "Apple Podcast", "Audio"],
    .bot: ["Bot", "Chatbot", "Automation"],
    .facebook: ["Facebook", "Social", "Social media"],
    .figma: ["Figma", "Design", "Prototyping"],
    .github: ["GitHub", "Code", "Repository"],
    .glassdoor: ["Glassdoor", "Jobs", "Reviews"],
    .globe: ["Language", "Web", "International"],
    .google: ["Google", "Search", "Find"],
    .googlePodcasts: ["Google Podcasts", "Audio", "Podcast"],
    .instagram: ["Instagram", "Social", "Photos"],
    .linkedin: ["LinkedIn", "Professional", "Network"],
    .messenger: ["Messenger", "Facebook", "Chat"],
    .openAIChatGPT: ["ChatGPT", "OpenAI", "AI"],
    .slack: ["Slack", "Team", "Messages"],
    .slideshare: ["SlideShare", "Presentations", "LinkedIn"],
    .soundcloud: ["SoundCloud", "Music", "Audio"],
    .spotify: ["Spotify", "Music", "Streaming"],
    .teams: ["Teams", "Microsoft", "Meeting"],
    .threads: ["Threads", "Instagram", "Social"],
    .tiktok: ["TikTok", "Video", "Social"],
    .weChat: ["WeChat", "China", "Messages"],
    .weibo: ["Weibo", "China", "Social"],
    .whatsapp: ["WhatsApp", "Messages", "Chat"],
    .windows: ["Windows", "Microsoft", "System"],
    .x: ["X", "Twitter", "Social"],
    .youtube: ["YouTube", "Video", "Streaming"],

    // MARK: Actions
    .addPlus: ["Add item", "Create new", "FAB"],
    .addToQueue: ["Add to queue", "Queue", "Playlist"],
    .alarm: ["Reminders", "Alerts", "Notifications"],
    .bold: ["Bold", "Formatting", "Text"],
    .bookOpen: ["Book", "Reading", "Content"],
    .bookmark: ["Save", "Favorites", "Reading list"],
    .building: ["Company", "Building", "Organization"],
    .bulb: ["Idea", "Lightbulb", "Insight"],
    .calendarAdd: ["Add event", "Schedule", "Date"],
    .calendarClose: ["Cancel event", "Remove date", "Calendar"],
    .calendarDays: ["Date", "Schedule", "Events"],
    .calendarOk: ["Event confirmed", "Scheduled", "Date"],
    .calendarWeek: ["Week view", "Weekly", "Calendar"],
    .chartBarVertical: ["Charts", "Analytics", "Dashboard"],
    .chartLine: ["Line chart", "Analytics", "Metrics"],
    .chartPie: ["Pie chart", "Analytics", "Distribution"],
    .check: ["Confirm", "Done", "Selection"],
    .checkAll: ["Select all", "Confirm all", "Batch"],
    .checkboxCheck: ["Checkbox checked", "Selection", "Task"],
    .checkboxUnchecked: ["Checkbox empty", "Selection", "Task"],
    .circleCheck: ["Success", "Validation", "Confirmation"],
    .circleHelp: ["Help", "FAQ", "Support"],
    .clock: ["Time", "Clock", "Schedule"],
    .close: ["Close", "Cancel", "Remove tag"],
    .code: ["Code", "Programming", "Dev"],
    .coffee: ["Coffee", "Break", "Rest"],
    .coffeToGo: ["Coffee to go", "Take away", "Drink"],
    .command: ["Command", "Shortcut", "Terminal"],
    .cookie: ["Cookie", "Privacy", "GDPR"],
    .copy: ["Copy", "Duplicate", "Clipboard"],
    .creditCard: ["Payment", "Wallet", "Finance"],
    .crop: ["Crop", "Trim", "Image editing"],
    .cupcake: ["Cupcake", "Birthday", "Celebration"],
    .desktopTower: ["Desktop", "Computer", "Hardware"],
    .devices: ["Devices", "Multi-device", "Responsive"],
    .doubleQuotes: ["Quote", "Citation", "Text"],
    .editPencil: ["Edit", "Modify", "Pen"],
    .editPencilLine: ["Edit", "Modify", "Write"],
    .filter: ["Filter", "Refine", "Advanced search"],
    .firstAid: ["First aid", "Health", "Emergency"],
    .flag: ["Flag", "Report", "Attention"],
    .font: ["Font", "Typography", "Text"],
    .gift: ["Gift", "Reward", "Promotion"],
    .heart: ["Like", "Favorite", "Health"],
    .hide: ["Hide", "Hide password", "Privacy"],
    .info: ["Information", "Tooltip", "Help"],
    .italic: ["Italic", "Formatting", "Text"],
    .keyboard: ["Keyboard", "Input", "Typing"],
    .label: ["Label", "Tag", "Classification"],
    .laptop: ["Laptop", "Computer", "Work"],
    .leaf: ["Sustainability", "Eco", "Nature"],
    .link: ["URL", "Share link", "Hyperlink"],
    .linkBreak: ["Broken link", "Disconnect", "URL"],
    .listAdd: ["Add to list", "New task", "To-do"],
    .listCheck: ["List done", "Checklist", "Task"],
    .listChecklist: ["Checklist", "Tasks", "List"],
    .listOrdered: ["Ordered list", "Numbered", "Sequence"],
    .listRemove: ["Remove from list", "Delete task", "To-do"],
    .lock: ["Security", "Locked", "Privacy"],
    .lockOpen: ["Unlocked", "No restriction", "Open"],
    .logOut: ["Log out", "Sign out", "Disconnect"],
    .magnifyingGlassBlock: ["Search blocked", "No results", "Find"],
    .magnifyingGlassMinus: ["Zoom out", "Reduce", "Search"],
    .magnifyingGlassPlus: ["Zoom in", "Enlarge", "Search"],
    .mobileButton: ["Mobile", "Phone", "App"],
    .moon: ["Dark mode", "Night", "Sleep"],
    .mouse: ["Mouse", "Cursor", "Interaction"],
    .move: ["Move", "Drag", "Reposition"],
    .note: ["Note", "Annotation", "Reminder"],
    .noteEdit: ["Edit note", "Annotation", "Write"],
    .noteSearch: ["Search note", "Find", "Annotation"],
    .notebook: ["Notebook", "Notes", "Journal"],
    .octagonWarning: ["Warning", "Attention", "Error"],
    .paragraph: ["Paragraph", "Formatting", "Text"],
    .planet: ["Planet", "Global", "World"],
    .printer: ["Print", "Printer", "Document"],
    .puzzle: ["Integration", "Plugin", "Extension"],
    .qrCode: ["QR Code", "Scan", "Link"],
    .radioFill: ["Radio selected", "Option", "Form"],
    .radioUnchecked: ["Radio empty", "Option", "Form"],
    .rainbow: ["Diversity", "Colors", "Creativity"],
    .redo: ["Redo", "Forward action", "History"],
    .removeMinus: ["Remove", "Decrease", "Minus"],
    .ruler: ["Ruler", "Measurement", "Design"],
    .save: ["Save", "Store", "Disk"],
    .searchMagnifyingGlass: ["Search", "Find", "Filter"],
    .selectMultiple: ["Select multiple", "Bulk selection", "Batch"],
    .settings: ["Settings", "Preferences", "Config"],
    .shoppingBag: ["Shopping bag", "Purchase", "E-commerce"],
    .shoppingCart: ["Cart", "Purchase", "E-commerce"],
    .show: ["View", "Show password", "Preview"],
    .star: ["Favorite", "Rating", "Highlight"],
    .strikethrough: ["Strikethrough", "Formatting", "Text"],
    .suitcase: ["Travel", "Business", "Luggage"],
    .sun: ["Light mode", "Brightness", "Day"],
    .switchLeft: ["Disable", "Toggle off", "Switch"],
    .switchRight: ["Enable", "Toggle on", "Switch"],
    .table: ["Table", "Data", "Grid"],
    .tableAdd: ["Add table", "New row", "Grid"],
    .tableRemove: ["Remove table", "Delete row", "Grid"],
    .tabletButton: ["Tablet", "iPad", "Device"],
    .tag: ["Tag", "Category", "Classification"],
    .text: ["Text", "Content", "Typography"],
    .textAlignCenter: ["Center align", "Alignment", "Text"],
    .textAlignJustify: ["Justify", "Alignment", "Text"],
    .textAlignLeft: ["Left align", "Alignment", "Text"],
    .textAlignRight: ["Right align", "Alignment", "Text"],
    .ticketVoucher: ["Ticket", "Voucher", "Coupon"],
    .trashEmpty: ["Delete", "Remove", "Trash"],
    .trashFull: ["Trash full", "Delete", "Remove"],
    .trendingDown: ["Trending down", "Decline", "Metrics"],
    .trendingUp: ["Trending up", "Growth", "Metrics"],
    .underline: ["Underline", "Formatting", "Text"],
    .undo: ["Undo", "Back action", "History"],
    .user: ["Profile", "Avatar", "Account"],
    .userAdd: ["Add user", "New member", "Invite"],
    .userCardID: ["ID card", "Identity", "Profile"],
    .userCheck: ["User approved", "Verified", "Confirmed"],
    .userClose: ["User removed", "Banned", "Blocked"],
    .userRemove: ["Remove user", "Delete member", "Account"],
    .userVoice: ["Narrator", "Accessibility", "Voice"],
    .users: ["Group", "Team", "Community"],
    .waterDrop: ["Water", "Hydration", "Sustainability"],
    .wifiHigh: ["Connection", "Network", "Internet"],
    .wifiOff: ["No WiFi", "Offline", "Disconnected"],
    .wifiProblem: ["WiFi problem", "Weak signal", "Connection issue"]
]
