import SwiftUI

// MARK: - Icon Category

enum IconCategory: Int, CaseIterable {
    case all
    case navigation
    case actions
    case communication
    case files
    case media
    case aiSocial

    var tabKey: String {
        switch self {
        case .all:           return "catalog.icon.category.all"
        case .navigation:    return "catalog.icon.category.navigation"
        case .actions:       return "catalog.icon.category.actions"
        case .communication: return "catalog.icon.category.communication"
        case .files:         return "catalog.icon.category.files"
        case .media:         return "catalog.icon.category.media"
        case .aiSocial:      return "catalog.icon.category.ai_social"
        }
    }

    var localizedLabel: String {
        NSLocalizedString(tabKey, comment: "")
    }
}

// MARK: - Category Map

// swiftlint:disable:next type_body_length
enum IconCategoryMap { // Exhaustive static category map — data-only, necessary length.
    static let map: [ZodiakIcon: IconCategory] = [
        // Navigation
        .arrowDown: .navigation,
        .arrowDownLeft: .navigation,
        .arrowDownRight: .navigation,
        .arrowDownUp: .navigation,
        .arrowLeft: .navigation,
        .arrowLeftRight: .navigation,
        .arrowRight: .navigation,
        .arrowUndoDownLeft: .navigation,
        .arrowUndoDownRight: .navigation,
        .arrowUndoUpLeft: .navigation,
        .arrowUndoUpRight: .navigation,
        .arrowUp: .navigation,
        .arrowUpLeft: .navigation,
        .arrowUpRight: .navigation,
        .arrowsReload01: .navigation,
        .arrowsReload02: .navigation,
        .chevronDown: .navigation,
        .chevronFirstPage: .navigation,
        .chevronLastPage: .navigation,
        .chevronLeft: .navigation,
        .chevronRight: .navigation,
        .chevronUp: .navigation,
        .compass: .navigation,
        .expand: .navigation,
        .externalLink: .navigation,
        .hamburger: .navigation,
        .house: .navigation,
        .mapPin: .navigation,
        .moreHorizontal: .navigation,
        .moreVertical: .navigation,
        // Navigation additions
        .map: .navigation,
        .moreGrid: .navigation,
        .navigation: .navigation,
        .shrink: .navigation,
        .sortAscending: .navigation,
        .sortDescending: .navigation,
        .unfoldLess: .navigation,
        .unfoldMore: .navigation,
        // Communication
        .bell: .communication,
        .bellNotification: .communication,
        .bellOff: .communication,
        .bellRing: .communication,
        .chatCircle: .communication,
        .chatCircleAdd: .communication,
        .chatCircleCheck: .communication,
        .chatCircleClose: .communication,
        .chatCircleDots: .communication,
        .chatCircleRemove: .communication,
        .chatConversationCircle: .communication,
        .headphones: .communication,
        .mail: .communication,
        .paperPlane: .communication,
        .phone: .communication,
        .share: .communication,
        // Communication additions
        .mailOpen: .communication,
        .mention: .communication,
        .paperclipAttachment: .communication,
        .shareAndroid: .communication,
        .shareiOSExport: .communication,
        // Files & Data
        .archive: .files,
        .data: .files,
        .download: .files,
        .downloadPackage: .files,
        .fileAdd: .files,
        .fileBlank: .files,
        .fileCheck: .files,
        .fileClose: .files,
        .fileCode: .files,
        .fileDocument: .files,
        .fileDownload: .files,
        .fileEdit: .files,
        .fileRemove: .files,
        .fileSearch: .files,
        .fileUpload: .files,
        .files: .files,
        .folder: .files,
        .folderAdd: .files,
        .folderCheck: .files,
        .folderClose: .files,
        .folderCode: .files,
        .folderDocument: .files,
        .folderDownload: .files,
        .folderEdit: .files,
        .folderOpen: .files,
        .folderRemove: .files,
        .folderSearch: .files,
        .folderUpload: .files,
        .folders: .files,
        .cloud: .files,
        .cloudAdd: .files,
        .cloudCheck: .files,
        .cloudClose: .files,
        .cloudDownload: .files,
        .cloudOff: .files,
        .cloudRemove: .files,
        .cloudUpload: .files,
        // Media
        .backward15: .media,
        .camera: .media,
        .forward: .media,
        .forward15: .media,
        .image: .media,
        .layers: .media,
        .monitorPlay: .media,
        .pause: .media,
        .play: .media,
        .swatchesPalette: .media,
        // Media additions
        .monitor: .media,
        .pauseFilled: .media,
        .playFilled: .media,
        .rewind: .media,
        .shuffle: .media,
        .skipBack: .media,
        .skipForward: .media,
        .speed: .media,
        .stop: .media,
        .stopFilled: .media,
        .volumeMax: .media,
        .volumeMin: .media,
        .volumeOff: .media,
        // AI & Social
        .ai: .aiSocial,
        .aiBrain: .aiSocial,
        .aiContent: .aiSocial,
        .aiEditing: .aiSocial,
        .aiGenerate: .aiSocial,
        .aiImage: .aiSocial,
        .aiLibrary: .aiSocial,
        .aiMagicWand: .aiSocial,
        .aiSearch: .aiSocial,
        .apple: .aiSocial,
        .applePodcast: .aiSocial,
        .bot: .aiSocial,
        .facebook: .aiSocial,
        .figma: .aiSocial,
        .github: .aiSocial,
        .glassdoor: .aiSocial,
        .globe: .aiSocial,
        .google: .aiSocial,
        .googlePodcasts: .aiSocial,
        .instagram: .aiSocial,
        .linkedin: .aiSocial,
        .messenger: .aiSocial,
        .openAIChatGPT: .aiSocial,
        .slack: .aiSocial,
        .slideshare: .aiSocial,
        .soundcloud: .aiSocial,
        .spotify: .aiSocial,
        .teams: .aiSocial,
        .threads: .aiSocial,
        .tiktok: .aiSocial,
        .weChat: .aiSocial,
        .weibo: .aiSocial,
        .whatsapp: .aiSocial,
        .windows: .aiSocial,
        .x: .aiSocial,
        .youtube: .aiSocial,
        // Actions
        .addPlus: .actions,
        .addToQueue: .actions,
        .alarm: .actions,
        .bold: .actions,
        .bookOpen: .actions,
        .bookmark: .actions,
        .building: .actions,
        .bulb: .actions,
        .calendarAdd: .actions,
        .calendarClose: .actions,
        .calendarDays: .actions,
        .calendarOk: .actions,
        .calendarWeek: .actions,
        .chartBarVertical: .actions,
        .chartLine: .actions,
        .chartPie: .actions,
        .check: .actions,
        .checkAll: .actions,
        .checkboxCheck: .actions,
        .checkboxUnchecked: .actions,
        .circleCheck: .actions,
        .circleHelp: .actions,
        .clock: .actions,
        .close: .actions,
        .code: .actions,
        .coffeToGo: .actions,
        .coffee: .actions,
        .command: .actions,
        .cookie: .actions,
        .copy: .actions,
        .creditCard: .actions,
        .crop: .actions,
        .cupcake: .actions,
        .desktopTower: .actions,
        .devices: .actions,
        .doubleQuotes: .actions,
        .editPencil: .actions,
        .editPencilLine: .actions,
        .filter: .actions,
        .firstAid: .actions,
        .flag: .actions,
        .font: .actions,
        .gift: .actions,
        .heart: .actions,
        .hide: .actions,
        .info: .actions,
        .italic: .actions,
        .keyboard: .actions,
        .label: .actions,
        .laptop: .actions,
        .leaf: .actions,
        .link: .actions,
        .linkBreak: .actions,
        .listAdd: .actions,
        .listCheck: .actions,
        .listChecklist: .actions,
        .listOrdered: .actions,
        .listRemove: .actions,
        .lock: .actions,
        .lockOpen: .actions,
        .logOut: .actions,
        .magnifyingGlassBlock: .actions,
        .magnifyingGlassMinus: .actions,
        .magnifyingGlassPlus: .actions,
        .mobileButton: .actions,
        .moon: .actions,
        .mouse: .actions,
        .move: .actions,
        .note: .actions,
        .noteEdit: .actions,
        .noteSearch: .actions,
        .notebook: .actions,
        .octagonWarning: .actions,
        .paragraph: .actions,
        .planet: .actions,
        .printer: .actions,
        .puzzle: .actions,
        .qrCode: .actions,
        .radioFill: .actions,
        .radioUnchecked: .actions,
        .rainbow: .actions,
        .redo: .actions,
        .removeMinus: .actions,
        .ruler: .actions,
        .save: .actions,
        .searchMagnifyingGlass: .actions,
        .selectMultiple: .actions,
        .settings: .actions,
        .shoppingBag: .actions,
        .shoppingCart: .actions,
        .show: .actions,
        .star: .actions,
        .strikethrough: .actions,
        .suitcase: .actions,
        .sun: .actions,
        .switchLeft: .actions,
        .switchRight: .actions,
        .table: .actions,
        .tableAdd: .actions,
        .tableRemove: .actions,
        .tabletButton: .actions,
        .tag: .actions,
        .text: .actions,
        .textAlignCenter: .actions,
        .textAlignJustify: .actions,
        .textAlignLeft: .actions,
        .textAlignRight: .actions,
        .ticketVoucher: .actions,
        .trashEmpty: .actions,
        .trashFull: .actions,
        .trendingDown: .actions,
        .trendingUp: .actions,
        .underline: .actions,
        .undo: .actions,
        .user: .actions,
        .userAdd: .actions,
        .userCardID: .actions,
        .userCheck: .actions,
        .userClose: .actions,
        .userRemove: .actions,
        .userVoice: .actions,
        .users: .actions,
        .waterDrop: .actions,
        .wifiHigh: .actions,
        .wifiOff: .actions,
        .wifiProblem: .actions
    ]
}
