package com.zodiak.android.feature.catalog.models

import androidx.compose.ui.graphics.Color
import com.zodiak.android.design_system.theme.ZodiakSemanticColors

enum class ColorTokenCategory(val titleKey: String) {
    BRAND("catalog.color.category_brand"),
    SURFACE("catalog.color.category_surface"),
    SURFACE_DECORATIVE("catalog.color.category_surface_decorative"),
    TEXT("catalog.color.category_text"),
    STATUS("catalog.color.category_status"),
    ACTION("catalog.color.category_action"),
    ACTION_WARNING("catalog.color.category_action_warning"),
    BORDER("catalog.color.category_border"),
    OVERLAY("catalog.color.category_overlay"),
    PRIMITIVE("catalog.color.category_primitive")
}

data class GuidelineReference(
    val sectionKey: String,
    val url: String,
    val excerptKey: String
) {
    companion object {
        val COLOR = GuidelineReference("guideline.color.section", "https://m3.material.io/styles/color/overview", "guideline.color.excerpt")
        val ACCESSIBILITY_CONTRAST = GuidelineReference("guideline.accessibility_contrast.section", "https://m3.material.io/foundations/accessible-design/accessibility-basics", "guideline.accessibility_contrast.excerpt")
        val INCLUSIVE_COLOR = GuidelineReference("guideline.inclusive_color.section", "https://m3.material.io/styles/color/system/how-the-system-works", "guideline.inclusive_color.excerpt")
        val DARK_MODE = GuidelineReference("guideline.dark_mode.section", "https://m3.material.io/styles/color/system/dark-theme", "guideline.dark_mode.excerpt")
        val MATERIALS = GuidelineReference("guideline.materials.section", "https://m3.material.io/styles/elevation/overview", "guideline.materials.excerpt")
        val INTERACTIVE_COLOR = GuidelineReference("guideline.interactive_color.section", "https://m3.material.io/styles/color/overview", "guideline.interactive_color.excerpt")
    }
}

data class ColorTokenDetail(
    val id: String,
    val name: String,
    val colorSelector: (ZodiakSemanticColors) -> Color,
    val primitiveRef: String,
    val isAdaptive: Boolean,
    val category: ColorTokenCategory,
    val intent: String,
    val usageKeys: List<String>,
    val doKeys: List<String>,
    val dontKeys: List<String>,
    val guideline: GuidelineReference,
    var descriptionKey: String = ""
)

object ColorTokenMetadata {
    val allEntries: List<ColorTokenDetail> = listOf(
        ColorTokenDetail(
            id = "brand",
            name = "Capgemini Logo",
            colorSelector = { it.brand },
            primitiveRef = "Blue.shade500 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.BRAND,
            intent = "Azul Capgemini — identidade visual corporativa primária.",
            usageKeys = listOf("token.brand.usage_0", "token.brand.usage_1", "token.brand.usage_2", "token.brand.usage_3"),
            doKeys = listOf("token.brand.do_0", "token.brand.do_1"),
            dontKeys = listOf("token.brand.dont_0", "token.brand.dont_1"),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "brandOrange",
            name = "Brand Orange",
            colorSelector = { it.brandOrange },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "background",
            name = "Cloud Lite",
            colorSelector = { it.background },
            primitiveRef = "Neutral.shade50 / Neutral.shade950 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Cor de fundo de página — camada mais externa da hierarquia de superfícies.",
            usageKeys = listOf("token.background.usage_0", "token.background.usage_1", "token.background.usage_2"),
            doKeys = listOf("token.background.do_0", "token.background.do_1"),
            dontKeys = listOf("token.background.dont_0"),
            guideline = GuidelineReference.MATERIALS
        ),
        ColorTokenDetail(
            id = "surface",
            name = "Page Background",
            colorSelector = { it.surface },
            primitiveRef = "White / Neutral.shade850 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Superfície de cards e painéis — uma camada acima de background.",
            usageKeys = listOf("token.surface.usage_0", "token.surface.usage_1", "token.surface.usage_2", "token.surface.usage_3"),
            doKeys = listOf("token.surface.do_0"),
            dontKeys = listOf("token.surface.dont_0"),
            guideline = GuidelineReference.MATERIALS
        ),
        ColorTokenDetail(
            id = "surfaceSmoke",
            name = "Smoke Lite",
            colorSelector = { it.surfaceSmoke },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Superfície smoke alternativa — hover de cards e seções de separação suave.",
            usageKeys = listOf("token.surfaceSmoke.usage_0", "token.surfaceSmoke.usage_1"),
            doKeys = listOf("token.surfaceSmoke.do_0"),
            dontKeys = listOf("token.surfaceSmoke.dont_0"),
            guideline = GuidelineReference.MATERIALS
        ),
        ColorTokenDetail(
            id = "surfaceFog",
            name = "Fog Lite",
            colorSelector = { it.surfaceFog },
            primitiveRef = "Neutral.shade50 / Neutral.shade900 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Superfície Fog — variante neutra para seções editoriais sem borda.",
            usageKeys = listOf("token.surfaceFog.usage_0", "token.surfaceFog.usage_1"),
            doKeys = listOf("token.surfaceFog.do_0"),
            dontKeys = listOf("token.surfaceFog.dont_0"),
            guideline = GuidelineReference.MATERIALS
        ),
        ColorTokenDetail(
            id = "surfaceCaribbean",
            name = "Caribbean Lite",
            colorSelector = { it.surfaceCaribbean },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Azul vibrante para seções de destaque editorial.",
            usageKeys = listOf("token.surfaceCaribbean.usage_0", "token.surfaceCaribbean.usage_1", "token.surfaceCaribbean.usage_2"),
            doKeys = listOf("token.surfaceCaribbean.do_0"),
            dontKeys = listOf("token.surfaceCaribbean.dont_0"),
            guideline = GuidelineReference.DARK_MODE
        ),
        ColorTokenDetail(
            id = "surfaceCaribbeanInverse",
            name = "Caribbean Lite Inverse",
            colorSelector = { it.surfaceCaribbeanInverse },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Versão invertida de surfaceCaribbean — para layouts invertidos onHeavy.",
            usageKeys = listOf("token.surfaceCaribbeanInverse.usage_0"),
            doKeys = listOf("token.surfaceCaribbeanInverse.do_0"),
            dontKeys = listOf("token.surfaceCaribbeanInverse.dont_0"),
            guideline = GuidelineReference.DARK_MODE
        ),
        ColorTokenDetail(
            id = "surfaceInk",
            name = "Ink Heavy",
            colorSelector = { it.surfaceInk },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "surfaceMarine",
            name = "Marine Heavy",
            colorSelector = { it.surfaceMarine },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Azul marinho — superfície onHeavy mais clara que surfaceInk.",
            usageKeys = listOf("token.surfaceMarine.usage_0", "token.surfaceMarine.usage_1"),
            doKeys = listOf("token.surfaceMarine.do_0"),
            dontKeys = listOf("token.surfaceMarine.dont_0"),
            guideline = GuidelineReference.DARK_MODE
        ),
        ColorTokenDetail(
            id = "surfaceAzur",
            name = "Azur Heavy",
            colorSelector = { it.surfaceAzur },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Azul Azur vibrante — superfície de destaque de marca.",
            usageKeys = listOf("token.surfaceAzur.usage_0", "token.surfaceAzur.usage_1"),
            doKeys = listOf("token.surfaceAzur.do_0"),
            dontKeys = listOf("token.surfaceAzur.dont_0"),
            guideline = GuidelineReference.DARK_MODE
        ),
        ColorTokenDetail(
            id = "surfaceAlwaysWhite",
            name = "Always White",
            colorSelector = { it.surfaceAlwaysWhite },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "surfaceAlwaysBlack",
            name = "Always Black",
            colorSelector = { it.surfaceAlwaysBlack },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "surfacePositive",
            name = "Positive",
            colorSelector = { it.surfacePositive },
            primitiveRef = "Green.shade50 / Green.shade900 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Fundo de sucesso — verde pálido para banners, badges e estados de confirmação.",
            usageKeys = listOf("token.surfacePositive.usage_0", "token.surfacePositive.usage_1", "token.surfacePositive.usage_2"),
            doKeys = listOf("token.surfacePositive.do_0", "token.surfacePositive.do_1"),
            dontKeys = listOf("token.surfacePositive.dont_0", "token.surfacePositive.dont_1"),
            guideline = GuidelineReference.INCLUSIVE_COLOR
        ),
        ColorTokenDetail(
            id = "surfaceNegative",
            name = "Negative",
            colorSelector = { it.surfaceNegative },
            primitiveRef = "Red.shade50 / Red.shade900 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "Fundo de erro/aviso — vermelho pálido para mensagens de alerta e campos com erro.",
            usageKeys = listOf("token.surfaceNegative.usage_0", "token.surfaceNegative.usage_1", "token.surfaceNegative.usage_2"),
            doKeys = listOf("token.surfaceNegative.do_0", "token.surfaceNegative.do_1"),
            dontKeys = listOf("token.surfaceNegative.dont_0", "token.surfaceNegative.dont_1"),
            guideline = GuidelineReference.INCLUSIVE_COLOR
        ),
        ColorTokenDetail(
            id = "surfaceDecorativeBrand",
            name = "Brand Blue",
            colorSelector = { it.surfaceDecorativeBrand },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE_DECORATIVE,
            intent = "Superfície decorativa azul de marca — para elementos editoriais e ilustrativos.",
            usageKeys = listOf("token.surfaceDecorativeBrand.usage_0", "token.surfaceDecorativeBrand.usage_1"),
            doKeys = listOf("token.surfaceDecorativeBrand.do_0"),
            dontKeys = listOf("token.surfaceDecorativeBrand.dont_0"),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "surfaceDecorativeOrange",
            name = "Brand Orange",
            colorSelector = { it.surfaceDecorativeOrange },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "textPrimary",
            name = "Primary",
            colorSelector = { it.textPrimary },
            primitiveRef = "Neutral.shade950 / Neutral.shade50 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Texto principal — máxima hierarquia tipográfica para títulos, corpo e labels.",
            usageKeys = listOf("token.textPrimary.usage_0", "token.textPrimary.usage_1", "token.textPrimary.usage_2"),
            doKeys = listOf("token.textPrimary.do_0"),
            dontKeys = listOf("token.textPrimary.dont_0", "token.textPrimary.dont_1"),
            guideline = GuidelineReference.ACCESSIBILITY_CONTRAST
        ),
        ColorTokenDetail(
            id = "textSecondary",
            name = "Secondary",
            colorSelector = { it.textSecondary },
            primitiveRef = "Neutral.shade500 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Texto secundário — hierarquia reduzida para metadados, legendas e descrições de suporte.",
            usageKeys = listOf("token.textSecondary.usage_0", "token.textSecondary.usage_1", "token.textSecondary.usage_2", "token.textSecondary.usage_3"),
            doKeys = listOf("token.textSecondary.do_0"),
            dontKeys = listOf("token.textSecondary.dont_0", "token.textSecondary.dont_1"),
            guideline = GuidelineReference.ACCESSIBILITY_CONTRAST
        ),
        ColorTokenDetail(
            id = "textInverse",
            name = "Inverse",
            colorSelector = { it.textInverse },
            primitiveRef = "Neutral.shade50 / Neutral.shade950 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Texto inverso — par de textPrimary para superfícies escuras onHeavy.",
            usageKeys = listOf("token.textInverse.usage_0", "token.textInverse.usage_1"),
            doKeys = listOf("token.textInverse.do_0"),
            dontKeys = listOf("token.textInverse.dont_0"),
            guideline = GuidelineReference.DARK_MODE
        ),
        ColorTokenDetail(
            id = "textDisabled",
            name = "Disabled",
            colorSelector = { it.textDisabled },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Texto desabilitado — indica que um elemento não é interativo.",
            usageKeys = listOf("token.textDisabled.usage_0", "token.textDisabled.usage_1", "token.textDisabled.usage_2"),
            doKeys = listOf("token.textDisabled.do_0", "token.textDisabled.do_1"),
            dontKeys = listOf("token.textDisabled.dont_0", "token.textDisabled.dont_1"),
            guideline = GuidelineReference.ACCESSIBILITY_CONTRAST
        ),
        ColorTokenDetail(
            id = "textAlwaysWhite",
            name = "Always White",
            colorSelector = { it.textAlwaysWhite },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "textAlwaysBlack",
            name = "Always Black",
            colorSelector = { it.textAlwaysBlack },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "textLink",
            name = "Link",
            colorSelector = { it.textLink },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Cor padrão de links inline — estado default, indica navegação.",
            usageKeys = listOf("token.textLink.usage_0", "token.textLink.usage_1"),
            doKeys = listOf("token.textLink.do_0"),
            dontKeys = listOf("token.textLink.dont_0", "token.textLink.dont_1"),
            guideline = GuidelineReference.INCLUSIVE_COLOR
        ),
        ColorTokenDetail(
            id = "textLinkHover",
            name = "Link Hover",
            colorSelector = { it.textLinkHover },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Hover de links — feedback visual ao passar o cursor.",
            usageKeys = listOf("token.textLinkHover.usage_0"),
            doKeys = listOf("token.textLinkHover.do_0"),
            dontKeys = listOf("token.textLinkHover.dont_0"),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "textLinkPressed",
            name = "Link Pressed",
            colorSelector = { it.textLinkPressed },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Pressed de links — feedback de toque.",
            usageKeys = listOf("token.textLinkPressed.usage_0"),
            doKeys = listOf("token.textLinkPressed.do_0"),
            dontKeys = listOf("token.textLinkPressed.dont_0"),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "textLinkInverse",
            name = "Link Inverse",
            colorSelector = { it.textLinkInverse },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Link em superfícies onHeavy — versão invertida de textLink.",
            usageKeys = listOf("token.textLinkInverse.usage_0"),
            doKeys = listOf("token.textLinkInverse.do_0"),
            dontKeys = listOf("token.textLinkInverse.dont_0"),
            guideline = GuidelineReference.DARK_MODE
        ),
        ColorTokenDetail(
            id = "textNegative",
            name = "Negative onLite",
            colorSelector = { it.textNegative },
            primitiveRef = "Red.shade800 / Red.shade200 · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.TEXT,
            intent = "Texto de erro — mensagens de validação e estados de falha.",
            usageKeys = listOf("token.textNegative.usage_0", "token.textNegative.usage_1", "token.textNegative.usage_2"),
            doKeys = listOf("token.textNegative.do_0", "token.textNegative.do_1"),
            dontKeys = listOf("token.textNegative.dont_0", "token.textNegative.dont_1"),
            guideline = GuidelineReference.INCLUSIVE_COLOR
        ),
        ColorTokenDetail(
            id = "textNegativeOnHeavy",
            name = "Negative onHeavy",
            colorSelector = { it.textNegativeOnHeavy },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "textPositive",
            name = "Positive",
            colorSelector = { it.textPositive },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "statusOnline",
            name = "Online",
            colorSelector = { it.statusOnline },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "statusAway",
            name = "Away",
            colorSelector = { it.statusAway },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "statusDoNotDisturb",
            name = "Do Not Disturb",
            colorSelector = { it.statusDoNotDisturb },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "statusOffline",
            name = "Offline",
            colorSelector = { it.statusOffline },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "actionWarningTint",
            name = "Action Warning Tint",
            colorSelector = { it.actionWarningTint },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "surfaceWarningTint",
            name = "Surface Warning Tint",
            colorSelector = { it.surfaceWarningTint },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "bannerSuccess",
            name = "Banner Success",
            colorSelector = { it.bannerSuccess },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "bannerWarning",
            name = "Banner Warning",
            colorSelector = { it.bannerWarning },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "bannerError",
            name = "Banner Error",
            colorSelector = { it.bannerError },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "actionPrimary",
            name = "Primary Default onLite",
            colorSelector = { it.actionPrimary },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION,
            intent = "Cor primária de ação — botões CTA, links e elementos interativos em superfícies claras.",
            usageKeys = listOf("token.actionPrimary.usage_0", "token.actionPrimary.usage_1", "token.actionPrimary.usage_2"),
            doKeys = listOf("token.actionPrimary.do_0"),
            dontKeys = listOf("token.actionPrimary.dont_0"),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionHover",
            name = "Primary Hover onLite",
            colorSelector = { it.actionHover },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION,
            intent = "Cor de hover de ações — escurece ao passar o cursor.",
            usageKeys = listOf("token.actionHover.usage_0", "token.actionHover.usage_1"),
            doKeys = listOf("token.actionHover.do_0"),
            dontKeys = listOf("token.actionHover.dont_0"),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionPressed",
            name = "Primary Pressed onLite",
            colorSelector = { it.actionPressed },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION,
            intent = "Cor de pressed — feedback de toque.",
            usageKeys = listOf("token.actionPressed.usage_0"),
            doKeys = listOf("token.actionPressed.do_0"),
            dontKeys = listOf("token.actionPressed.dont_0"),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionDisabled",
            name = "Disabled",
            colorSelector = { it.actionDisabled },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION,
            intent = "Fundo de elementos desabilitados — botões e controles inativos.",
            usageKeys = listOf("token.actionDisabled.usage_0", "token.actionDisabled.usage_1"),
            doKeys = listOf("token.actionDisabled.do_0"),
            dontKeys = listOf("token.actionDisabled.dont_0"),
            guideline = GuidelineReference.ACCESSIBILITY_CONTRAST
        ),
        ColorTokenDetail(
            id = "actionDisabledContent",
            name = "Disabled Content",
            colorSelector = { it.actionDisabledContent },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "actionActive",
            name = "Active",
            colorSelector = { it.actionActive },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "actionFocus",
            name = "Focus onLite",
            colorSelector = { it.actionFocus },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION,
            intent = "Anel de foco — acessibilidade de teclado e VoiceOver.",
            usageKeys = listOf("token.actionFocus.usage_0", "token.actionFocus.usage_1", "token.actionFocus.usage_2"),
            doKeys = listOf("token.actionFocus.do_0", "token.actionFocus.do_1"),
            dontKeys = listOf("token.actionFocus.dont_0"),
            guideline = GuidelineReference.ACCESSIBILITY_CONTRAST
        ),
        ColorTokenDetail(
            id = "actionFocusOnHeavy",
            name = "Focus onHeavy",
            colorSelector = { it.actionFocusOnHeavy },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION,
            intent = "Anel de foco em superfícies onHeavy.",
            usageKeys = listOf("token.actionFocusOnHeavy.usage_0"),
            doKeys = listOf("token.actionFocusOnHeavy.do_0"),
            dontKeys = listOf("token.actionFocusOnHeavy.dont_0"),
            guideline = GuidelineReference.ACCESSIBILITY_CONTRAST
        ),
        ColorTokenDetail(
            id = "actionPrimaryOnPhoto",
            name = "Primary onPhoto",
            colorSelector = { it.actionPrimaryOnPhoto },
            primitiveRef = "White · fixo",
            isAdaptive = false,
            category = ColorTokenCategory.ACTION,
            intent = "Ação primária sobre imagem fotográfica — branco fixo sobre qualquer foto.",
            usageKeys = listOf("token.actionPrimaryOnPhoto.usage_0", "token.actionPrimaryOnPhoto.usage_1"),
            doKeys = listOf("token.actionPrimaryOnPhoto.do_0"),
            dontKeys = listOf("token.actionPrimaryOnPhoto.dont_0"),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionWarning",
            name = "Warning Default",
            colorSelector = { it.actionWarning },
            primitiveRef = "Red.shade500 / White · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION_WARNING,
            intent = "Cor primária de ações de aviso — botão warning. Vermelho no Zodiak.",
            usageKeys = listOf("token.actionWarning.usage_0", "token.actionWarning.usage_1"),
            doKeys = listOf("token.actionWarning.do_0"),
            dontKeys = listOf("token.actionWarning.dont_0"),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionWarningContent",
            name = "Warning Content",
            colorSelector = { it.actionWarningContent },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION_WARNING,
            intent = "Texto/ícone sobre fundo de warning — contraste adequado sobre actionWarning.",
            usageKeys = listOf("token.actionWarningContent.usage_0"),
            doKeys = listOf("token.actionWarningContent.do_0"),
            dontKeys = listOf(),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionWarningHover",
            name = "Warning Hover",
            colorSelector = { it.actionWarningHover },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION_WARNING,
            intent = "Hover do botão de warning.",
            usageKeys = listOf("token.actionWarningHover.usage_0"),
            doKeys = listOf("token.actionWarningHover.do_0"),
            dontKeys = listOf(),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionWarningHoverOutline",
            name = "Warning Hover Outline",
            colorSelector = { it.actionWarningHoverOutline },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION_WARNING,
            intent = "Borda do botão warning secundário em hover.",
            usageKeys = listOf("token.actionWarningHoverOutline.usage_0"),
            doKeys = listOf("token.actionWarningHoverOutline.do_0"),
            dontKeys = listOf(),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionWarningPressed",
            name = "Warning Pressed",
            colorSelector = { it.actionWarningPressed },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION_WARNING,
            intent = "Pressed do botão de warning.",
            usageKeys = listOf("token.actionWarningPressed.usage_0"),
            doKeys = listOf("token.actionWarningPressed.do_0"),
            dontKeys = listOf(),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionWarningPressedOutline",
            name = "Warning Pressed Outline",
            colorSelector = { it.actionWarningPressedOutline },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION_WARNING,
            intent = "Borda do botão warning secundário em pressed.",
            usageKeys = listOf("token.actionWarningPressedOutline.usage_0"),
            doKeys = listOf("token.actionWarningPressedOutline.do_0"),
            dontKeys = listOf(),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionWarningSecondary",
            name = "Warning Secondary Default",
            colorSelector = { it.actionWarningSecondary },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION_WARNING,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "actionWarningSecondaryHover",
            name = "Warning Secondary Hover",
            colorSelector = { it.actionWarningSecondaryHover },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION_WARNING,
            intent = "Hover do botão warning secundário.",
            usageKeys = listOf("token.actionWarningSecondaryHover.usage_0"),
            doKeys = listOf("token.actionWarningSecondaryHover.do_0"),
            dontKeys = listOf(),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionPrimaryOnHeavy",
            name = "Primary Default onHeavy",
            colorSelector = { it.actionPrimaryOnHeavy },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "actionHoverOnHeavy",
            name = "Primary Hover onHeavy",
            colorSelector = { it.actionHoverOnHeavy },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.ACTION,
            intent = "Hover de ações em superfícies onHeavy.",
            usageKeys = listOf("token.actionHoverOnHeavy.usage_0"),
            doKeys = listOf("token.actionHoverOnHeavy.do_0"),
            dontKeys = listOf(),
            guideline = GuidelineReference.INTERACTIVE_COLOR
        ),
        ColorTokenDetail(
            id = "actionPressedOnHeavy",
            name = "Primary Pressed onHeavy",
            colorSelector = { it.actionPressedOnHeavy },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "borderPrimary",
            name = "Primary",
            colorSelector = { it.borderPrimary },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.BORDER,
            intent = "Borda padrão — divisores, contornos de cards e campos de formulário.",
            usageKeys = listOf("token.borderPrimary.usage_0", "token.borderPrimary.usage_1", "token.borderPrimary.usage_2"),
            doKeys = listOf("token.borderPrimary.do_0"),
            dontKeys = listOf("token.borderPrimary.dont_0", "token.borderPrimary.dont_1"),
            guideline = GuidelineReference.MATERIALS
        ),
        ColorTokenDetail(
            id = "borderSecondary",
            name = "Secondary",
            colorSelector = { it.borderSecondary },
            primitiveRef = "colorset · adaptável",
            isAdaptive = true,
            category = ColorTokenCategory.BORDER,
            intent = "Borda sutil — separadores de menor hierarquia.",
            usageKeys = listOf("token.borderSecondary.usage_0", "token.borderSecondary.usage_1"),
            doKeys = listOf("token.borderSecondary.do_0"),
            dontKeys = listOf("token.borderSecondary.dont_0"),
            guideline = GuidelineReference.MATERIALS
        ),
        ColorTokenDetail(
            id = "pageOverlay",
            name = "Page Overlay",
            colorSelector = { it.pageOverlay },
            primitiveRef = "",
            isAdaptive = true,
            category = ColorTokenCategory.SURFACE,
            intent = "",
            usageKeys = listOf(),
            doKeys = listOf(),
            dontKeys = listOf(),
            guideline = GuidelineReference.COLOR
        ),
        ColorTokenDetail(
            id = "heroPhotographic",
            name = "Hero Photographic",
            colorSelector = { it.heroPhotographic },
            primitiveRef = "Overlay.black75 · fixo",
            isAdaptive = false,
            category = ColorTokenCategory.OVERLAY,
            intent = "Overlay fotográfico — gradiente escuro sobre imagens hero para legibilidade do texto.",
            usageKeys = listOf("token.heroPhotographic.usage_0"),
            doKeys = listOf("token.heroPhotographic.do_0"),
            dontKeys = listOf("token.heroPhotographic.dont_0"),
            guideline = GuidelineReference.MATERIALS
        ),
    )
    val all: Map<String, ColorTokenDetail> = allEntries.associateBy { it.id }
}
